### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by SaynaEbrahimi** [pierre-si/cord#1]
Hi, thank you for sharing your code! Do you mind adding a license to your code so that everyone including companies can use it? A simple MIT license or Apache 2.0 would do it for example. Thank you!

**Comment by pierre-si** [comment]
Hi @SaynaEbrahimi ,
Thank you for your message, I'm happy you find the code useful!
I added a license.

**Comment by SaynaEbrahimi** [comment]
Thank you so much! This is very helpful!
